// Replaces fabricated seed data with the artist's real artwork texts (from Drive docx).
// Bios are explicitly-marked DRAFT placeholders — no invented awards/exhibitions/dates.
import fs from 'node:fs'

const env = Object.fromEntries(
  fs.readFileSync(new URL('../.env.local', import.meta.url), 'utf8')
    .split('\n').filter(l => l.includes('=') && !l.startsWith('#'))
    .map(l => [l.slice(0, l.indexOf('=')).trim(), l.slice(l.indexOf('=') + 1).trim().replace(/^["']|["']$/g, '')])
)
const URL_ = env.NEXT_PUBLIC_SUPABASE_URL
const KEY = env.SUPABASE_SERVICE_ROLE_KEY
const H = { apikey: KEY, Authorization: `Bearer ${KEY}`, 'Content-Type': 'application/json' }

async function api(path, opts = {}) {
  const r = await fetch(`${URL_}/rest/v1/${path}`, { headers: H, ...opts })
  const t = await r.text()
  if (!r.ok) throw new Error(`${opts.method ?? 'GET'} ${path} → ${r.status} ${t}`)
  return t ? JSON.parse(t) : null
}

const DRAFT_TR = '⚠️ TASLAK — bu metin farazi bir yer tutucudur, sanatçının onayıyla değiştirilecektir.'
const DRAFT_EN = '⚠️ DRAFT — this text is a hypothetical placeholder, to be replaced with the artist\'s own words.'

// --- 1. Clear fabricated data -------------------------------------------------
console.log('Silinen uydurma kayıtlar:')
for (const t of ['product_images', 'products', 'exhibitions', 'portfolio_items']) {
  const before = await api(`${t}?select=id`)
  await api(`${t}?id=gt.0`, { method: 'DELETE' })
  console.log(`  ${t}: ${before.length} kayıt silindi`)
}

// --- 2. Artists: real first names, DRAFT bios, no invented credentials --------
const artists = [
  {
    slug: 'melike', name_tr: 'Melike', name_en: 'Melike',
    bio_tr: `${DRAFT_TR}\n\nSeramik ve pişmiş toprak üzerine çalışan bir sanatçı. Üretiminde geleneksel şekillendirme ve yüzey tekniklerini çağdaş bir yorumla bir araya getiriyor; malzemenin dokusunu ve pişirimin bıraktığı izleri kompozisyonun taşıyıcı unsuru olarak ele alıyor.\n\n(Gerçek biyografi, eğitim ve sergi bilgileri sanatçıdan alınacaktır.)`,
    bio_en: `${DRAFT_EN}\n\nAn artist working in ceramics and fired clay, bringing together traditional forming and surface techniques with a contemporary reading. The texture of the material and the traces left by firing are treated as load-bearing elements of the composition.\n\n(Actual biography, education and exhibition history to be supplied by the artist.)`,
  },
  {
    slug: 'seref', name_tr: 'Şeref', name_en: 'Şeref',
    bio_tr: `${DRAFT_TR}\n\nSeramik alanında üreten bir sanatçı. Form, oran ve yüzey ilişkisi üzerine çalışıyor; antik kap formlarının biçim dilini kendi pratiği içinde yeniden ele alıyor.\n\n(Gerçek biyografi, eğitim ve sergi bilgileri sanatçıdan alınacaktır.)`,
    bio_en: `${DRAFT_EN}\n\nAn artist producing in ceramics, working on the relationship between form, proportion and surface, and revisiting the formal language of ancient vessel shapes within his own practice.\n\n(Actual biography, education and exhibition history to be supplied by the artist.)`,
  },
]
for (const a of artists) {
  const existing = await api(`artists?slug=eq.${a.slug}&select=id`)
  if (existing.length) {
    await api(`artists?slug=eq.${a.slug}`, { method: 'PATCH', body: JSON.stringify({ ...a, email: null, photo_url: null }) })
    console.log(`Sanatçı güncellendi: ${a.slug}`)
  } else {
    await api('artists', { method: 'POST', body: JSON.stringify(a) })
    console.log(`Sanatçı eklendi: ${a.slug}`)
  }
}

// --- 3. Real artworks — descriptions are the ARTIST'S OWN words (Drive docx) --
const CAT = 'Antik Dönem Replikaları'
const MED_TR = 'Terra sigillata tekniği'
const MED_EN = 'Terra sigillata technique'

const artworks = [
  {
    slug: 'afrodit-ve-kaz', title_tr: 'Afrodit ve Kaz', title_en: 'Aphrodite and the Goose',
    description_tr: `Kap formu: Kylix · Dönemi: MÖ 5. yüzyıl · Teknik: Attika Beyaz Zemin Seramiği (White Ground)\n\nBu kompozisyonun kökeni MÖ 460–450 tarihli, Pistoxenos Ressamı'na atfedilen Attika beyaz zeminli tabaktır. Replikada Afrodit uzun khiton giysisi ve başındaki taçla betimlenmiş; altında ise kutsal hayvanı olan kaz yer alıyor. Kazın açılmış kanatları, tanrıçanın göksel ve zarif doğasını vurguluyor.\n\nAfrodit denince çoğu kişi güvercin ya da kuğuyu düşünür; ancak kaz da Afrodit'in kutsal hayvanlarından biridir. Sevgi, evlilik ve bereketi simgeler; su ile ilişkisi nedeniyle tanrıçanın denizden doğuşuna gönderme yapar. Antik Yunan sanatında özellikle MÖ 5. yüzyılda Afrodit bazen kazın üzerinde otururken veya onunla birlikte yürürken resmedilmiştir.\n\nPistoxenos Ressamı'nın üslubunda zarif ve ince çizgiler, beyaz zemin üzerine hafif kırmızı, kahverengi ve siyah konturlar, figürlerde sakin ve şiirsel bir anlatım ile giysi kıvrımlarının akıcı verilişi öne çıkar. Mitolojik sahneler dramatik değil, dingin bir estetikle sunulur.`,
    description_en: `Vessel form: Kylix · Period: 5th century BC · Technique: Attic White Ground\n\nThe origin of this composition is an Attic white-ground plate of 460–450 BC attributed to the Pistoxenos Painter. In the replica, Aphrodite is depicted in a long chiton with a diadem, and beneath her is the goose, her sacred animal. The spread wings of the goose emphasise the celestial and graceful nature of the goddess.\n\nMost people associate Aphrodite with the dove or the swan, but the goose is also one of her sacred animals. It symbolises love, marriage and fertility, and through its association with water it alludes to the goddess's birth from the sea. In Greek art, particularly in the 5th century BC, Aphrodite is sometimes shown seated upon or walking alongside a goose.\n\nThe style of the Pistoxenos Painter is marked by delicate, fine lines, light red, brown and black contours on a white ground, a calm and poetic treatment of the figures, and fluid drapery folds — mythological scenes presented through a serene rather than dramatic aesthetic.`,
  },
  {
    slug: 'europa', title_tr: 'Europa\'nın Zeus Tarafından Kaçırılışı', title_en: 'The Abduction of Europa by Zeus',
    description_tr: `Teknik: Terra sigillata · Kırmızı figürlü Attika geleneği\n\nKompozisyonun merkezinde genç bir kadın olan Europa bulunuyor. Yanındaki beyaz boğa, gerçekte tanrı Zeus'tur. Europa'nın boğanın sırtına yerleşmiş biçimde gösterilmesi, mitin en tanınmış anını temsil eder. Rüzgârda savrulan pelerini ve hareket hâlindeki boğa, sahneye dinamizm kazandırır. Çevredeki meander ve dalga motifleri, Antik Yunan seramiklerinin karakteristik bezeme anlayışını yansıtır.\n\nEuropa, Fenike kralı Agenor'un kızıdır. Zeus ona âşık olur, ancak doğrudan yaklaşmak yerine uysal ve bembeyaz bir boğa kılığına girer. Europa boğanın sırtına oturduğu anda Zeus denize doğru koşar ve onu Girit Adası'na götürür. Bu birliktelikten Minos, Rhadamanthys ve Sarpedon doğar; özellikle Minos, Labirent ve Minotor efsanelerinin merkezindeki figür olacaktır.\n\nBu sahne yalnızca bir kaçırılma hikâyesi değildir: tanrısal gücün insan dünyasına müdahalesi, deniz yolculuğu ve kültürlerin taşınması, Doğu'dan Batı'ya geçişin simgesi olarak yorumlanır. Nitekim "Avrupa" kıtasının adı da Europa'dan gelir.`,
    description_en: `Technique: Terra sigillata · Attic red-figure tradition\n\nAt the centre of the composition is the young woman Europa. The white bull beside her is in fact the god Zeus. Europa shown settled on the bull's back represents the best-known moment of the myth. Her wind-blown cloak and the moving bull lend dynamism to the scene, while the surrounding meander and wave motifs reflect the characteristic decorative idiom of Greek pottery.\n\nEuropa was the daughter of Agenor, king of Phoenicia. Zeus fell in love with her but, rather than approaching directly, took the form of a gentle, snow-white bull. The moment Europa sat on his back, Zeus ran to the sea and carried her to Crete. From this union were born Minos, Rhadamanthys and Sarpedon — Minos in particular becoming the central figure of the Labyrinth and Minotaur legends.\n\nThe scene is not merely a story of abduction: it is read as the intervention of divine power in the human world, as sea voyage and the movement of cultures, and as a symbol of passage from East to West. The continent of Europe takes its name from Europa.`,
  },
  {
    slug: 'menad', title_tr: 'Menad', title_en: 'Maenad',
    description_tr: `Teknik: Terra sigillata · Attika kırmızı figür üslubu\n\nMainadlar, şarap ve coşkunun tanrısı Dionysos'un kadın takipçileridir. Antik Yunan seramiklerinde onları dans ederken, avlanırken ya da vahşi hayvanlarla birlikte görmek oldukça yaygındır.\n\nKompozisyonda dikkat çeken ikonografik özellikler: omuza alınan benekli leopar postu (nebris), Mainadların en karakteristik giysisidir ve Dionysos kültüyle doğrudan ilişkilidir. Sol eldeki, ucunda çam kozalağı bulunan uzun asa — thyrsos — Dionysos'un kutsal simgesidir. Sağ elden tutulan benekli yırtıcı hayvan yine Dionysos'un kutsal hayvanlarından biridir; Mainadlar antik sanatta sık sık panterlerle birlikte tasvir edilir. Hareketli giysiler ve uçuşan saçlar ise trans hâlindeki dansı ve coşkulu ruh hâlini ifade eder.\n\nMainadlar yalnızca dans eden kadınlar değildir. Dionysos kültünde doğanın dizginlenemeyen gücünü, coşkuyu (ekstasis), esrimeyi ve insan ile doğa arasındaki sınırların ortadan kalkmasını temsil ederler. Bu nedenle antik sanatçılar onları çoğu zaman hareket hâlinde, rüzgârla savrulan giysiler ve canlı bir ritim içinde betimlemişlerdir.`,
    description_en: `Technique: Terra sigillata · Attic red-figure style\n\nMaenads were the female followers of Dionysos, god of wine and ecstasy. In Greek pottery they are commonly shown dancing, hunting, or in the company of wild animals.\n\nThe striking iconographic features here: the spotted leopard skin (nebris) over the shoulder is the most characteristic garment of the Maenads and is directly linked to the Dionysian cult. The long staff in the left hand, tipped with a pine cone — the thyrsos — is the sacred emblem of Dionysos. The spotted predator held in the right hand is likewise one of his sacred animals; Maenads are frequently depicted with panthers in ancient art. The animated drapery and flying hair express the dance of trance and an exultant state of mind.\n\nMaenads are not merely dancing women. Within the Dionysian cult they represent the untameable force of nature, ecstasy (ekstasis), rapture, and the dissolution of the boundary between human and nature. For this reason ancient artists most often portrayed them in motion, with wind-blown garments and a vivid rhythm.`,
  },
  {
    slug: 'thetis', title_tr: 'Thetis', title_en: 'Thetis',
    description_tr: `Teknik: Terra sigillata · Kırmızı zemin üzerine beyaz figür\n\nThetis, deniz tanrısı Nereus ile Doris'in kızlarından biridir ve Nereidlerin (deniz perilerinin) en ünlüsüdür. Aynı zamanda Akhilleus'un annesi olarak Homeros'un destanlarında önemli bir yere sahiptir.\n\nBu replikada Thetis'i tanımlayan en önemli unsur, balıklarla birlikte betimlenmiş olmasıdır. Figürün iki elinde tuttuğu büyük balıklar, onun deniz dünyasıyla olan bağını simgeler; etrafında yüzen diğer balıklar sahnenin deniz ortamında geçtiğini açıkça ifade eder. Hafif hareket hâlindeki giysisi ve zarif duruşu, Nereid tasvirlerinin tipik özelliklerindendir. Kırmızı zemin üzerine beyaz figür tekniği, Geç Arkaik ve Erken Klasik dönem Attika seramiklerinde görülen dekoratif anlayışı hatırlatır; dış bordürdeki dama (checkerboard) deseni ise bazı Attika kyliks ve tabaklarında kullanılan süsleme şemalarından biridir.\n\nThetis'in etrafında pek çok önemli mit gelişir. Zeus ve Poseidon ona ilgi duyar; ancak bir kehanet, doğuracağı oğlun babasından daha güçlü olacağını söyler. Bu yüzden Thetis ölümlü kahraman Peleus ile evlendirilir ve bu evlilikten Akhilleus doğar. Oğlunu ölümsüz yapmak için onu Styx Nehri'ne batırır; yalnızca topuğundan tuttuğu için o kısım savunmasız kalır.`,
    description_en: `Technique: Terra sigillata · White figure on red ground\n\nThetis was one of the daughters of the sea god Nereus and Doris, and the most famous of the Nereids. As the mother of Achilles she holds an important place in the Homeric epics.\n\nThe defining element of this replica is that Thetis is depicted with fish. The large fish held in each hand symbolise her bond with the world of the sea, while the other fish swimming around her make clear that the scene takes place underwater. Her lightly moving garment and graceful stance are typical of Nereid depictions. The white-figure-on-red-ground technique recalls the decorative approach of Late Archaic and Early Classical Attic pottery, and the checkerboard pattern of the outer border is one of the ornamental schemes used on certain Attic kylikes and plates.\n\nMany important myths surround Thetis. Zeus and Poseidon both desired her, but a prophecy held that the son she bore would be greater than his father. She was therefore married to the mortal hero Peleus, and from this marriage Achilles was born. To make her son immortal she dipped him in the river Styx; because she held him by the heel, that part remained vulnerable.`,
  },
  {
    slug: 'siren', title_tr: 'Siren', title_en: 'Siren',
    description_tr: `Teknik: Terra sigillata\n\nBu figür, ikonografik özelliklerine bakıldığında bir Siren tasviridir. Kadın başı ve gövdesi ile kuş kanatları birlikte verilmiş; dizlerin altından itibaren kuş bacakları ve pençeleri görülüyor. Ayakların altında küçük bir kaya ya da zemin motifi var — Sirenler antik sanatta çoğunlukla kayalık kıyılarla ilişkilendirilir. Figürün sakin ve ön cepheye yakın duruşu, Geç Klasik ve Helenistik dönemde mezar stelleri ve seramiklerde görülen Siren betimlemelerine benzemektedir.\n\nAntik Yunan mitolojisinde Sirenler kadın başlı, kuş gövdeli mitolojik varlıklardır; büyüleyici şarkılarıyla denizcileri kendilerine çekerler. En ünlü anlatıları, Odysseia destanında Odysseus'un Sirenlerin şarkısını dinlemek için kendini geminin direğine bağlatmasıdır. Antik Yunan sanatında yalnızca baştan çıkarıcı varlıklar değil, ölüm, ruhun yolculuğu ve öteki dünya ile ilişkilendirilen semboller olarak da kullanılmışlardır; bu nedenle mezar anıtlarında da sıkça görülürler.\n\nKanatlardaki beyaz noktalı süslemeler, drapenin ince kıvrımları, dış bordürdeki bitkisel rumi benzeri bezemeler ve spiral friz, kompozisyona hem antik hem de dekoratif bir karakter kazandırıyor.`,
    description_en: `Technique: Terra sigillata\n\nJudging by its iconographic features, this figure is a depiction of a Siren. A woman's head and torso are combined with bird wings; from below the knees the legs and talons of a bird appear. Beneath the feet is a small rock or ground motif — Sirens in ancient art are usually associated with rocky shores. The calm, near-frontal stance of the figure resembles Siren depictions found on Late Classical and Hellenistic grave stelae and pottery.\n\nIn Greek mythology Sirens are creatures with a woman's head and a bird's body, drawing sailors to themselves with their enchanting song. Their most famous appearance is in the Odyssey, where Odysseus has himself bound to the mast in order to hear their song. In Greek art they were used not only as seductive beings but also as symbols associated with death, the journey of the soul and the other world, and for this reason appear frequently on funerary monuments.\n\nThe white dotted ornaments on the wings, the fine folds of the drapery, the vegetal rumi-like decoration of the outer border and the spiral frieze give the composition both an ancient and a decorative character.`,
  },
  {
    slug: 'aulos-calan-menad-kylix', title_tr: 'Aulos Çalan Menad — Kylix', title_en: 'Maenad Playing the Aulos — Kylix',
    description_tr: `Kap formu: Kylix (tondo kompozisyonu) · Teknik: Terra sigillata\n\nFigür, iki borulu bir aulos (çift kamışlı flüt) çalıyor. Antik Yunan'da aulos, flütten farklı olarak kamışlı nefesli bir çalgıdır ve özellikle Dionysos şenliklerinde, tiyatroda ve dinsel törenlerde kullanılırdı. Figür uzun bir khiton giymiş, sırtında benekli bir nebris (geyik ya da panter postu) taşıyor; ön taraftaki bitkisel motif büyük olasılıkla asma dalı veya sarmaşıktır. Bu ayrıntıların tümü Dionysos kültüyle ilişkiyi güçlendirir.\n\nİkonografik değerlendirme, figürün aulos çalan bir Mainad olduğu yönündedir: hayvan postu taşıması, bitkisel motifin Dionysos'u çağrıştırması, aulos'un Dionysos kültünün vazgeçilmez çalgısı olması ve duruşun yürüyen bir alay sahnesini andırması bu okumayı destekler. Alternatif olarak profesyonel bir kadın aulos sanatçısı (auletris) da olabilir.\n\nOrijinal antik kylix, geniş ağızlı, sığ gövdeli, ince ayaklı ve iki yatay kulplu bir şarap kadehidir. İç yüzeyinin ortasındaki yuvarlak resim alanına tondo denir; içki içildikçe tondo yavaş yavaş görünür ve resim adeta izleyiciye ortaya çıkar. Bu çalışmada da merkezde bir tondo bulunuyor ve figür bu dairesel alana yerleştirilmiş. Ancak kulpların daha kalın, gövdenin daha derin olması nedeniyle eser, birebir bir Attika kylixinden ziyade kylix kompozisyonunun çağdaş bir yorumu olarak durmaktadır.`,
    description_en: `Vessel form: Kylix (tondo composition) · Technique: Terra sigillata\n\nThe figure plays a double-piped aulos. Unlike the flute, the aulos is a reed wind instrument, used especially at Dionysian festivals, in the theatre and in religious ceremonies. The figure wears a long chiton and carries a spotted nebris (deer or panther skin) on the back; the vegetal motif at the front is most likely a vine or ivy branch. All of these details strengthen the connection to the Dionysian cult.\n\nThe iconographic reading is that the figure is a Maenad playing the aulos: the animal skin, the Dionysian associations of the vegetal motif, the aulos as the indispensable instrument of the cult, and a stance suggesting a procession all support this. Alternatively she may be a professional female aulos player (auletris).\n\nThe original ancient kylix is a wine cup with a wide mouth, shallow body, slender foot and two horizontal handles. The circular picture field at the centre of its interior is called the tondo; as the wine is drunk the tondo gradually appears, the image revealing itself to the viewer. This work also has a tondo at its centre with the figure placed within that circular field. However, as the handles are thicker and the body deeper, the piece stands as a contemporary interpretation of the kylix composition rather than a literal Attic kylix.`,
  },
  {
    slug: 'geometrik-donem-toren-kabi', title_tr: 'Geometrik Dönem Tören Kabı', title_en: 'Geometric Period Ceremonial Vessel',
    description_tr: `Dönemi: Geç Geometrik Dönem (yaklaşık MÖ 760–700) · Teknik: Terra sigillata\n\nBu eser, Geometrik Dönem bezeme anlayışını yansıtan bir replikadır. İlk bakışta belirgin bir mitolojik sahne yerine, tamamen dekoratif ve sembolik bir kompozisyon görülür.\n\nKompozisyon üç ana bölümden oluşuyor. Merkezdeki ışınsal rozet (güneş çiçeği), Geometrik Dönem seramiklerinde en sık görülen motiflerden biridir; güneş, yaşamın merkezi, kozmik düzen ve sonsuz döngü olarak yorumlanmıştır. Merkezden dışarı yayılan radyal siyah şeritler ışın, hareket, düzen ve ritim duygusu oluşturur; geometrik sanatın temel özelliği olan tekrar ve simetri burada açıkça görülür. Dış kuşakta ise dönüşümlü olarak su kuşları, uzun boyunlu kuşlar, palmet benzeri yaprak motifleri, spiral bezemeler ve haç biçimli rozetler yer alır. Geometrik Dönem'de kuşlar gökyüzü, yolculuk, ruh ve doğa ile ilişkilendirilirdi.\n\nBu bezeme dili büyük olasılıkla Geç Geometrik Dönem Attika seramiklerinden esinlenmiştir — henüz kırmızı figür ya da siyah figür tekniği ortaya çıkmadan önce Yunan seramiklerinde bu tür geometrik süslemeler hâkimdi. Terra sigillata uygulaması açısından fırça çizgilerinin netliği, dairesel kompozisyonun korunması ve merkezden dışarı yayılan ritim, antik örneklerin karakterini iyi yansıtmaktadır.`,
    description_en: `Period: Late Geometric (c. 760–700 BC) · Technique: Terra sigillata\n\nThis piece is a replica reflecting the decorative idiom of the Geometric Period. Rather than a distinct mythological scene, what we see is an entirely decorative and symbolic composition.\n\nThe composition consists of three main parts. The radiating rosette at the centre is one of the most frequent motifs on Geometric pottery, interpreted as the sun, the centre of life, cosmic order and the eternal cycle. The radial black bands spreading outward create a sense of ray, movement, order and rhythm; repetition and symmetry, the fundamental characteristics of Geometric art, are clearly visible. The outer band carries alternating water birds, long-necked birds, palmette-like leaf motifs, spiral ornaments and cross-shaped rosettes. In the Geometric Period birds were associated with the sky, with journey, with the soul and with nature.\n\nThis decorative language most likely draws on Late Geometric Attic pottery — before the red-figure or black-figure techniques had emerged, ornament of this kind dominated Greek ceramics. In terms of the terra sigillata application, the clarity of the brushwork, the preservation of the circular composition and the rhythm radiating from the centre reflect the character of the ancient examples well.`,
  },
  {
    slug: 'geometrik-donem-tabak', title_tr: 'Geometrik Dönem Tabak', title_en: 'Geometric Period Plate',
    description_tr: `Dönemi: Geometrik Dönem (MÖ 900–700) · Teknik: Terra sigillata\n\nBu eserde kuş frizi yerine tamamen geometrik motiflere yer verilmiştir. Bu tip kompozisyonlar Antik Yunan'ın Geometrik Dönemi estetiğini oldukça iyi yansıtır. Tabakta belirgin bir figür ya da mitolojik sahne yoktur; anlatım tamamen sembolik ve ritmiktir.\n\nMerkezdeki ışınsal rozet, Geometrik Dönem'in en karakteristik motiflerinden biridir ve güneşi, kozmik düzeni, yaşam döngüsünü ve evrenin merkezini sembolize ettiği düşünülür. Bu motif yalnızca Yunan sanatında değil, Ege ve Anadolu'nun Erken Demir Çağı bezemelerinde de görülür. Merkezden dışarı yayılan koyu radyal bantlar hareket, ışık, düzen ve simetri fikrini güçlendirir; geometrik sanatın temel ilkesi olan tekrar burada açıkça görülmektedir.\n\nDış kuşakta palmet veya tomurcuk benzeri yaprak motifleri, spiral (volüt) motifleri, üçgenler, haç biçimli rozetler ve paralel çizgiler yer alır — bunların hepsi Geometrik Dönem seramik repertuarının temel bezeme elemanlarıdır. Üçgenler dağ veya mimariyi, spiral sonsuzluğu ve sürekliliği, rozet güneşi, yaprak ve palmet ise yaşamı ve doğayı çağrıştıran semboller olarak yorumlanabilir.`,
    description_en: `Period: Geometric (900–700 BC) · Technique: Terra sigillata\n\nIn this piece, purely geometric motifs take the place of a bird frieze. Compositions of this type reflect the aesthetic of the Greek Geometric Period particularly well. There is no distinct figure or mythological scene on the plate; the expression is entirely symbolic and rhythmic.\n\nThe radiating rosette at the centre is one of the most characteristic motifs of the period, thought to symbolise the sun, cosmic order, the cycle of life and the centre of the universe. This motif appears not only in Greek art but also in the Early Iron Age ornament of the Aegean and Anatolia. The dark radial bands spreading outward reinforce the idea of movement, light, order and symmetry; repetition, the founding principle of Geometric art, is clearly evident.\n\nThe outer band carries palmette or bud-like leaf motifs, spiral (volute) motifs, triangles, cross-shaped rosettes and parallel lines — all fundamental elements of the Geometric ceramic repertoire. Triangles may evoke mountains or architecture, the spiral infinity and continuity, the rosette the sun, and leaf and palmette life and nature.`,
  },
  {
    slug: 'kylix-krater-can-krater', title_tr: 'Kylix Krater (Çan Krater)', title_en: 'Kylix Krater (Bell Krater)',
    description_tr: `Teknik: Siyah figür · Özgün örnek: Attika siyah figür geleneği, yaklaşık MÖ 550–520\n\nOrtadaki sakallı figür uzun ve gösterişli bir himation giymiş. İki kolunu yana açmış olması, savaşan ya da tartışan iki taraf arasında hakemlik, arabuluculuk veya hüküm verme jesti olarak okunabilir. Sol ve sağdaki figürler tam teçhizatlı hoplit savaşçılardır; ikisinin de mızrak ve kalkan taşıması, bunun sıradan bir düello değil, kahramanlar arasındaki bir karşılaşma olduğunu düşündürür.\n\nHerakles'i vazo resimlerinde tanımamızı sağlayan ikonografik özellikler arasında omuzlarda ya da başta taşınan Nemea Aslanı postu, en belirgin simgesi olan topuz ve bazen yay ile oklar bulunur. Bu çalışmada sol savaşçının omzunda veya sırtında hayvan postuna benzeyen bir ayrıntı görülmektedir. Ortadaki figür Zeus olabilir: vazo resimlerinde bazen asa (skeptron) veya şimşek demeti ile gösterilir, fakat bazı sahnelerde yalnızca hakem ve otorite figürü olarak da resmedilmiştir; özellikle tanrılar ile kahramanlar arasındaki anlaşmazlıklarda kollarını iki yana açmış biçimde betimlenebilir.\n\nÜslup açısından figürlerde kazıma çizgileri oldukça belirgin, giysilerde beyaz ek boya kullanılmıştır. Meander bordürü ve lotus-palmet frizi Arkaik dönem bezeme anlayışını yansıtır.`,
    description_en: `Technique: Black figure · Original model: Attic black-figure tradition, c. 550–520 BC\n\nThe bearded figure at the centre wears a long and elaborate himation. His arms spread to either side may be read as a gesture of arbitration, mediation or judgement between two contending or disputing parties. The figures to left and right are fully equipped hoplite warriors; that both carry spear and shield suggests this is not an ordinary duel but an encounter between heroes.\n\nThe iconographic features by which Herakles is recognised in vase painting include the skin of the Nemean Lion worn over the shoulders or head, his most distinctive attribute the club, and sometimes bow and arrows. In this work a detail resembling an animal skin can be seen on the left warrior's shoulder or back. The central figure may be Zeus: in vase painting he is sometimes shown with a sceptre or thunderbolt, but in some scenes he appears purely as a figure of arbitration and authority, and may be depicted with arms spread in disputes between gods and heroes.\n\nStylistically the incised lines on the figures are pronounced, and added white pigment is used on the garments. The meander border and lotus-palmette frieze reflect the decorative idiom of the Archaic period.`,
  },
  {
    slug: 'volutlu-krater', title_tr: 'Volütlü Krater', title_en: 'Volute Krater',
    description_tr: `Teknik: Terra sigillata · Kırmızı figür tekniğinin yorumu\n\nA yüzü — Bu yüzde dört figür görülüyor. İki yanda uzun asalar taşıyan kadın figürleri bulunuyor; soldaki figürlerden biri elini kaldırmış durumda ve figürlerin tamamı uzun himationlar giymiş. Bu yüz ilk bakışta dramatik bir mitolojik olaydan çok ritüel veya dinsel bir alayı andırıyor. Burada iki olasılık öne çıkıyor: Eleusis Gizemleri ile ilgili bir sahne ya da Demeter–Persephone kültüne ait bir geçit töreni. Asa taşıyan kadınlar rahibeler veya kült görevlileri olabilir.\n\nB yüzü — Ortadaki genç figürün özellikleri Apollon'un klasik ikonografisiyle uyumludur: genç ve sakalsız yüz, başında taç veya çelenk, sol elinde defne çelengi, sağ eli kutsama veya konuşma jestiyle kaldırılmış. Yanındaki geyik, Apollon'un doğrudan simgesi olmasa da onun doğa ve av kültüyle, özellikle ikiz kardeşi Artemis'le olan ilişkisini çağrıştırır. Soldaki tahtta oturan figür büyük olasılıkla bir tanrıçadır ve Leto olabilir; bu durumda sahne Leto, Apollon ve Artemis'ten oluşan Delos Üçlüsünü temsil ediyor olabilir. İkinci bir olasılık ise Demeter ve Triptolemos sahnesidir: bazı Attika vazolarında Demeter tahtta oturur, genç Triptolemos onun önünde durur ve Persephone yanında yer alır.\n\nÜslup açısından palmet frizi oldukça kaliteli uygulanmış, volüt kulplar ayrıntılı işlenmiş ve gövde oranları Attika volütlü kraterlerini başarılı biçimde yansıtmaktadır.`,
    description_en: `Technique: Terra sigillata · An interpretation of the red-figure technique\n\nSide A — Four figures appear on this face. Female figures carrying long staffs stand at either side; one of the figures on the left has raised her hand, and all wear long himatia. At first glance this face suggests a ritual or religious procession rather than a dramatic mythological event. Two possibilities stand out: a scene relating to the Eleusinian Mysteries, or a procession belonging to the Demeter–Persephone cult. The staff-bearing women may be priestesses or cult officials.\n\nSide B — The features of the young central figure accord with the classical iconography of Apollo: a young, beardless face, a diadem or wreath on the head, a laurel wreath in the left hand, the right hand raised in a gesture of blessing or speech. The deer beside him, while not a direct attribute of Apollo, evokes his connection with nature and the hunt, and particularly with his twin sister Artemis. The figure seated on the throne to the left is most likely a goddess and may be Leto, in which case the scene could represent the Delian Triad of Leto, Apollo and Artemis. A second possibility is a scene of Demeter and Triptolemos: on some Attic vases Demeter is seated on a throne, the young Triptolemos stands before her, and Persephone is at her side.\n\nStylistically the palmette frieze is executed to a high standard, the volute handles are worked in detail, and the proportions of the body successfully reflect Attic volute kraters.`,
  },
]

let n = 0
for (const a of artworks) {
  await api('products', {
    method: 'POST',
    body: JSON.stringify({
      artist_id: null,            // AÇIK SORU: hangi eser Melike'nin hangisi Şeref'in — Çağrı ayıracak
      slug: a.slug,
      title_tr: a.title_tr, title_en: a.title_en,
      description_tr: a.description_tr, description_en: a.description_en,
      category: CAT,
      year: null,                 // üretim yılı bilinmiyor — uydurulmadı
      medium_tr: MED_TR, medium_en: MED_EN,
      dimensions_tr: null, dimensions_en: null,   // ölçüler bilinmiyor — uydurulmadı
      price: null, currency: 'TRY',               // katalog formatı; fiyat kararı Çağrı'da
      is_sold: false, is_visible: true,
    }),
  })
  n++
}
console.log(`\n${n} gerçek eser eklendi (kategori: ${CAT})`)
console.log('Eser açıklamaları sanatçının kendi metinlerinden (Drive/Replikalar hakkında.docx) alındı.')
